export default  [
    {
        id:1,
        name:'Programming',
        icon:'/coding.jpg',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/health.png',
        prompt:''
    },
    {
        id:1,
        name:'Creative',
        icon:'/creative.png',
        prompt:''
    }
]